sudo: required
services:
  - docker

before_install:
  - docker build -t theuncleshege/multi-docker-client -f ./client/Dockerfile.dev ./client

script:
  - docker run theuncleshege/multi-docker-client npm run test -- --coverage

after_success:
  - docker build -t theuncleshege/multi-docker-client ./client
  - docker build -t theuncleshege/multi-docker-api ./api
  - docker build -t theuncleshege/multi-docker-worker ./worker
  - docker build -t theuncleshege/multi-docker-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push theuncleshege/multi-docker-client
  - docker push theuncleshege/multi-docker-api
  - docker push theuncleshege/multi-docker-worker
  - docker push theuncleshege/multi-docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-596870276118"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
